// <auto-generated />
namespace BookAndEquipmentLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changeassetyeartonullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeassetyeartonullable));
        
        string IMigrationMetadata.Id
        {
            get { return "201803271152270_change asset year to nullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
